{{if and (eq .Values.istio.istioProvider "ossm3") (ne .Values.kuadrant.operatorName "authorino-operator") }}
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.istio.namespace }}
  values:
{{ if eq .Values.kuadrant.enableObservability true }}
    meshConfig:
      defaultConfig:
        tracing: { }
      enableTracing: true
      extensionProviders:
        - name: jaeger-otlp
          opentelemetry:
            port: 4317
            service: jaeger-collector.tools.svc.cluster.local
        - name: json-access-log
          envoyFileAccessLog:
            logFormat:
              labels:
                method: "%REQ(:METHOD)%"
                route_name: "%ROUTE_NAME%"
                authority: "%REQ(:AUTHORITY)%"
                path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                response_flags: "%RESPONSE_FLAGS%"
                start_time: "%START_TIME%"
                request_id: "%REQ(X-REQUEST-ID)%"
                response_code: "%RESPONSE_CODE%"
                upstream_host: "%UPSTREAM_HOST%"
                bytes_sent: "%BYTES_SENT%"
                user_agent: "%REQ(USER-AGENT)%"
                duration: "%DURATION%"
                bytes_received: "%BYTES_RECEIVED%"
                upstream_cluster: "%UPSTREAM_CLUSTER%"
                protocol: "%PROTOCOL%"
                upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            path: /dev/stdout
{{ end }}
    global:
      proxy:
        componentLogLevel: "wasm:debug"
    pilot:
      autoscaleMin: 2
  version: {{ .Values.istio.ossm3.version }}
{{ end }}