{{ if ne .Values.kuadrant.operatorName "authorino-operator" }}
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant-sample
  namespace: {{ .Values.kuadrant.namespace }}
spec:
{{ if eq .Values.kuadrant.enableObservability true }}
  observability:
    dataPlane:
      defaultLevels:
        - debug: 'true'
      httpHeaderIdentifier: x-request-id
    enable: true
    tracing:
      defaultEndpoint: 'rpc://jaeger-collector.tools.svc.cluster.local:4317'
      insecure: true
{{ end }}
{{- $clusterVersion := (lookup "config.openshift.io/v1" "ClusterVersion" "" "version") -}}
{{- $ocpVersionOk := false -}}
{{- if $clusterVersion -}}
  {{- $ocpVersionOk = semverCompare ">=4.20.0-0" $clusterVersion.status.desired.version -}}
{{- end -}}
{{ if and .Values.kuadrant.developerPortal (eq .Values.kuadrant.developerPortal.enabled true) $ocpVersionOk }}
  components:
    developerPortal:
      enabled: true
{{ end }}
{{ end }}
